"""
expand_ontology_local.py — Free, rule-based ontology expander.

No API key required. Uses keyword matching on English verse translations to
assign known concept instances from the existing ontology. Generates valid
OWL 2 Turtle triples for all verses not yet in gita_ontology.ttl.

Honesty note (for paper): triples are generated by deterministic keyword rules
applied to authoritative English translations, not inferred by an LLM.
Every concept assignment is traceable to the specific keyword patterns below.

Usage:
    python backend/scripts/expand_ontology_local.py [--dry-run] [--limit N]
"""

import csv, re, argparse
from pathlib import Path
from rdflib import Graph, Namespace, RDF

ROOT     = Path(__file__).resolve().parents[2]
TTL_PATH = ROOT / "Data" / "ontology" / "gita_ontology.ttl"
CSV_PATH = ROOT / "Data" / "corpus" / "Bhagwad_Gita.csv"

GITA_PREFIX = "@prefix gita: <http://example.org/gita#> .\n"

# ── Concept → keyword patterns (applied to lowercase English meaning) ──────────
# Each tuple: (concept_uri, [keywords_any_of])
# A verse gets a concept triple if ANY keyword appears in its English meaning.
CONCEPT_RULES = [
    # Yoga Paths (use _inst suffix — matches TTL definition)
    ("KarmaYoga_inst",  ["selfless action", "karma yoga", "nishkama", "perform your duty",
                         "right to perform", "prescribed duties", "without attachment to fruits",
                         "action without desire", "fruit of action", "fruits of action",
                         "yagna", "yajna", "sacrifice"]),
    ("JnanaYoga_inst",  ["knowledge", "wisdom", "jnana", "wise", "knower", "self-knowledge",
                         "discrimination", "discern", "understand", "comprehend", "intellect",
                         "buddhi", "true knowledge", "knowing the self"]),
    ("DhyanaYoga_inst", ["meditation", "dhyana", "meditate", "concentrate", "contemplat",
                         "steady mind", "fixed mind", "yogi", "samadhi", "withdraw the senses",
                         "practice yoga", "sit in meditation"]),
    ("BhaktiYoga_inst", ["devotion", "devotee", "worship", "love", "bhakti", "surrender",
                         "beloved", "dear to me", "dearest", "i am dear", "faith",
                         "always think of me", "fix mind on me"]),

    # Practices (no _inst)
    ("NishkamaKarma",   ["without attachment", "not entitled to fruits", "right to perform",
                         "do not desire", "desireless", "detached from results",
                         "renounce the fruits", "without expectation"]),
    ("Vairagya",        ["renunciation", "detachment", "vairagya", "abandon", "give up",
                         "renounce", "relinquish", "non-attachment", "dispassion"]),
    ("Abhyasa",         ["practice", "repeated", "constant practice", "abhyasa",
                         "again and again", "persist", "perseverance"]),
    ("Samata",          ["equanimity", "equal", "sama", "sameness", "balanced",
                         "treat alike", "pleasure and pain", "heat and cold",
                         "success and failure", "neither joy nor grief"]),
    ("Buddhi",          ["intellect", "discriminative intelligence", "purified intellect",
                         "resolute intellect", "single-pointed intellect",
                         "buddhi", "reasoning faculty"]),

    # Attainments (no _inst)
    ("ChittaShuddhi",   ["purification", "purified", "pure mind", "cleanse",
                         "purity of mind", "inner purification"]),
    ("Sthitaprajna",    ["steady wisdom", "steady-minded", "sthitaprajna",
                         "one of steady wisdom", "wise one", "unmoved",
                         "stable intellect", "stable in wisdom"]),
    ("Samadhi",         ["samadhi", "trance", "absorption", "superconscious",
                         "merged in", "unified state", "deepest meditation"]),
    ("AtmaJnana",       ["self", "soul", "atma", "atman", "eternal self",
                         "imperishable", "never born", "never dies",
                         "indestructible soul", "individual self", "true self"]),
    ("Moksha",          ["liberation", "freedom", "moksha", "mukti", "emancipation",
                         "final liberation", "ultimate freedom", "released",
                         "attain brahman", "supreme abode", "divine abode"]),

    # Downfall Causes (no _inst)
    ("Kama",            ["desire", "craving", "lust", "kama", "greed", "longing",
                         "attachment to sense", "sense pleasure", "covet"]),
    ("Krodha",          ["anger", "wrath", "krodha", "rage", "fury", "angry"]),
    ("Moha",            ["delusion", "confusion", "bewilderment", "illusion",
                         "moha", "delusive", "deluded"]),
    ("BuddhiNasha",     ["destruction of intellect", "intellect is destroyed",
                         "buddhi is lost", "wisdom is destroyed", "buddhinasha",
                         "loss of memory", "ruined", "downfall"]),

    # Gunas (no _inst)
    ("Sattva",          ["sattva", "sattvic", "goodness", "purity", "light",
                         "mode of goodness", "peaceful", "knowledge and happiness"]),
    ("Rajas",           ["rajas", "rajasic", "passion", "activity", "restless",
                         "mode of passion", "selfish action", "feverish"]),
    ("Tamas",           ["tamas", "tamasic", "ignorance", "darkness", "inertia",
                         "mode of ignorance", "dull", "sloth", "delusion"]),

    # Ethical Concepts (mixed _inst)
    ("Svadharma",       ["own duty", "svadharma", "own dharma", "prescribed duty",
                         "natural duty", "inherent duty", "caste duty",
                         "better is one's own", "better to die in own"]),
    ("Sannyasa_inst",   ["renunciant", "sannyasa", "sannyasi", "order of renunciation",
                         "renounced order", "monk", "ascetic"]),
]

# Chapters that need a declaration (already in TTL: 2,3,4,5,6,7,12)
# We declare all 18 for completeness.
CHAPTER_NAMES = {
    1:  "Arjuna Vishada Yoga",
    2:  "Sankhya Yoga",
    3:  "Karma Yoga",
    4:  "Jnana Karma Sannyasa Yoga",
    5:  "Karma Sannyasa Yoga",
    6:  "Dhyana Yoga",
    7:  "Jnana Vijnana Yoga",
    8:  "Aksara Brahma Yoga",
    9:  "Raja Vidya Raja Guhya Yoga",
    10: "Vibhuti Yoga",
    11: "Vishwarupa Darshana Yoga",
    12: "Bhakti Yoga",
    13: "Kshetra Kshetrajna Vibhaga Yoga",
    14: "Gunatraya Vibhaga Yoga",
    15: "Purushottama Yoga",
    16: "Daivasura Sampad Vibhaga Yoga",
    17: "Shraddhatraya Vibhaga Yoga",
    18: "Moksha Sannyasa Yoga",
}


def strip_prefix(text: str) -> str:
    return re.sub(r'^[\d]+\.\d+\s*', '', (text or "")).strip()


def load_existing_keys() -> set:
    g = Graph()
    g.parse(str(TTL_PATH), format="turtle")
    GITA = Namespace("http://example.org/gita#")
    return {str(s).split("#")[-1] for s in g.subjects(RDF.type, GITA.Verse)}


def load_existing_chapters() -> set:
    g = Graph()
    g.parse(str(TTL_PATH), format="turtle")
    GITA = Namespace("http://example.org/gita#")
    return {str(s).split("#")[-1] for s in g.subjects(RDF.type, GITA.Chapter)}


def match_concepts(text: str) -> list:
    text_lower = text.lower()
    matched = []
    for concept_uri, keywords in CONCEPT_RULES:
        if any(kw in text_lower for kw in keywords):
            matched.append(concept_uri)
    return matched


def generate_triples(ch: str, v: str, eng: str, hi: str,
                     existing_chapters: set) -> list:
    triples = []
    key = f"Verse_{ch}_{v}"
    ch_key = f"Chapter_{ch}"

    # Core verse declaration
    triples.append(f"gita:{key}  a gita:Verse ;")
    triples.append(f"    gita:verseNumber {v} ;")
    triples.append(f"    gita:belongsToChapter gita:{ch_key} .")

    # Concept triples
    concepts = match_concepts(eng + " " + hi)
    for c in concepts:
        triples.append(f"gita:{key}  gita:teaches  gita:{c} .")

    # Chapter declaration (if not already in ontology)
    if ch_key not in existing_chapters:
        ch_num = int(ch)
        name = CHAPTER_NAMES.get(ch_num, f"Chapter {ch}")
        triples.append(f'gita:{ch_key}  a gita:Chapter ;')
        triples.append(f'    rdfs:label "{name}"^^xsd:string ;')
        triples.append(f'    gita:chapterNumber {ch} .')
        existing_chapters.add(ch_key)  # prevent duplicates within this run

    return triples


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="Print triples, don't write to file")
    parser.add_argument("--limit", type=int, default=0,
                        help="Max new verses to process (0=all)")
    parser.add_argument("--output", default=None,
                        help="Write to this file instead of appending to TTL")
    args = parser.parse_args()

    print("Loading existing ontology…")
    existing_keys = load_existing_keys()
    existing_chapters = load_existing_chapters()
    print(f"  {len(existing_keys)} verses already in corpus")

    rows = []
    with open(str(CSV_PATH), encoding="utf-8") as f:
        for r in csv.DictReader(f):
            ch, v = r.get("Chapter", ""), r.get("Verse", "")
            key = f"Verse_{ch}_{v}"
            if key not in existing_keys and ch and v:
                rows.append(r)

    if args.limit:
        rows = rows[:args.limit]

    print(f"  {len(rows)} new verses to expand")

    all_triples = []
    concept_count = 0
    zero_concept = []

    for r in rows:
        ch  = r.get("Chapter", "").strip()
        v   = r.get("Verse", "").strip()
        eng = strip_prefix(r.get("EngMeaning", ""))
        hi  = strip_prefix(r.get("HinMeaning", ""))

        triples = generate_triples(ch, v, eng, hi, existing_chapters)
        all_triples.extend(triples)
        all_triples.append("")  # blank line between verse blocks

        n_concepts = sum(1 for t in triples if "gita:teaches" in t)
        concept_count += n_concepts
        if n_concepts == 0:
            zero_concept.append(f"Verse_{ch}_{v}")

    print(f"\n  Generated {len([t for t in all_triples if t.strip()])} triple lines")
    print(f"  Concept assignments: {concept_count}")
    if zero_concept:
        print(f"  Verses with NO concept match ({len(zero_concept)}): "
              f"{', '.join(zero_concept[:10])}{'…' if len(zero_concept)>10 else ''}")

    if not all_triples:
        print("Nothing to write.")
        return

    block = "\n".join(all_triples)

    if args.dry_run:
        print("\n── DRY RUN ── first 40 lines of output:\n")
        for line in block.splitlines()[:40]:
            print(line)
        print(f"\n[dry-run] Would append {len(rows)} verse blocks to {TTL_PATH}")
        return

    out_path = Path(args.output) if args.output else TTL_PATH
    with open(str(out_path), "a", encoding="utf-8") as f:
        f.write(f"\n# ── Rule-based expansion: {len(rows)} verses ──────────────\n")
        f.write(block)
    print(f"\nAppended {len(rows)} verse blocks to {out_path}")
    print("Restart the Flask server so get_kg() reloads the updated TTL.")


if __name__ == "__main__":
    main()
